// Elements that are not interactive/clickable and are suitable for use as context (e.g., excludes img, input, button, video, iframe, etc.)
export const ContextualTextElementTypes = [
  "div",
  "span",
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "table",
  "tr",
  "td",
  "th",
  "ul",
  "ol",
  "li",
  "a",
  "blockquote",
  "code",
  "pre",
  "small",
  "strong",
  "em",
  "sub",
  "sup",
  "strong",
  "b",
] as const;

export const InvalidContextualTextElementText = [
  "jump to",
  "jump to content",
  "main menu",
  "navigation",
  "log in",
  "sign in",
  "sign up",
  "register",
  "login",
  "logout",
  "account",
  "profile",
  "settings",
  "help",
  "support",
  "contact",
  "about",
  "privacy",
  "terms",
  "cookie",
  "policy",
  "copyright",
  "disclaimer",
  "legal",
  "notice",
  "faq",
  "shipping",
  "returns",
  "refunds",
  "warranty",
  "guarantee",
  "quality",
  "authenticity",
  "authentic",
  "verified",
  "trust",
  "safe",
  "secure",
  "privacy",
  "terms",
  "cookie",
  "policy",
  "copyright",
  "disclaimer",
  "legal",
  "notice",
  "faq",
  "shipping",
  "returns",
  "refunds",
  "warranty",
  "guarantee",
  "quality",
  "authenticity",
];

export const InvalidContextualTextElementSelectors = [
  // Language/localization elements
  { type: "class", value: "interlanguage-link" },
  { type: "class", value: "lang-selector" },
  { type: "class", value: "language-list" },
  { type: "class", value: "mw-portlet-lang" },

  // Navigation and menu elements
  { type: "class", value: "navbar" },
  { type: "class", value: "nav" },
  { type: "class", value: "navigation" },
  { type: "class", value: "menu" },
  { type: "class", value: "sidebar" },
  { type: "class", value: "breadcrumb" },
  { type: "class", value: "pagination" },

  // Header and footer elements
  { type: "class", value: "header" },
  { type: "class", value: "footer" },
  { type: "class", value: "site-header" },
  { type: "class", value: "site-footer" },

  // Hidden/utility elements
  { type: "class", value: "hidden" },
  { type: "class", value: "sr-only" },
  { type: "class", value: "screen-reader-only" },
  { type: "class", value: "visually-hidden" },
  { type: "class", value: "skip-link" },

  // Advertisement and tracking
  { type: "class", value: "ad" },
  { type: "class", value: "ads" },
  { type: "class", value: "advertisement" },
  { type: "class", value: "google-ads" },
  { type: "class", value: "banner" },

  // Social media and sharing
  { type: "class", value: "social" },
  { type: "class", value: "share" },
  { type: "class", value: "social-share" },

  // Cookie notices and popups
  { type: "class", value: "cookie" },
  { type: "class", value: "popup" },
  { type: "class", value: "modal" },
  { type: "class", value: "overlay" },

  // Wikipedia specific
  { type: "class", value: "mw-editsection" },
  { type: "class", value: "mw-headline" },
  { type: "class", value: "navbox" },
  { type: "class", value: "infobox" },

  // Common layout elements
  { type: "id", value: "header" },
  { type: "id", value: "footer" },
  { type: "id", value: "navigation" },
  { type: "id", value: "sidebar" },
  { type: "id", value: "menu" },
];
